configfile: "config/config_mcclintock.yaml"

notification_email=config["email"]


include:    "rules/common.smk"
include:    "rules/alignment.smk"
include:    "rules/sv_call.smk"
include:    "rules/phasing.smk"
include:    "rules/annotation.smk"
include:    "rules/cleanup_cleaner.smk"
include:    "rules/makePlots.smk"
include:    "rules/qc_alignment.smk"
include:    "rules/adaptive_sampling.smk"
include:    "rules/cnv_call.smk"
include:    "rules/cDNA.smk"



rule all:
    input:
        get_targets_new
        #get_targets_transcriptome

onsuccess: shell("""echo "alignment snake has stopped after succesfully creating all targets" """)
    
onerror: shell( """echo "alignment snake encountered an error and did not complete" """)