samples: config/NSC0114_StJude_config.tsv
targetfile: config/targets.txt
strategy: RU
threads: 50
refgenome: /n/dat/hg38/hg38.no_alt.fa
ontmmifile: /n/dat/hg38/hg38.no_alt.mmi
input_dir: /waldo/bam_files_unaligned
working_dir: /n/alignments_inprogress/NSC0114_StJude
final_dir: /n/alignments/NSC0114_StJude
project: NSC0114_StJude
bedfiledir: /n/alignments/bed_targets
clairmodelpath: /n/dat/clair3
conda_alignment: alignmentCalling
conda_rust: rust_plus
conda_trio: clair3Trio
conda_vep: vep-110.1
conda_bcftools: bcftools-1.19 
vep_caches_path: /n/dat/vep
vep_data_path: /n/dat/annotationData
