samples: config/NSC0114_StJude_config.tsv
targetfile: config/targets.txt
strategy: RU
threads: 50
refgenome: /data/dat/hg38/hg38.no_alt.fa
ontmmifile: /data/dat/hg38/hg38.no_alt.mmi
input_dir: /waldo/bam_files_unaligned
working_dir: /data/alignments/NSC0114_StJude
final_dir: /n/alignments/NSC0114_StJude
project: NSC0114_StJude
bedfiledir: /n/alignments/bed_targets
clairmodelpath: /home/shared/resources
conda_alignment: alignment_snake
conda_rust: rust_plus
conda_trio: clair3Trio
conda_vep: vep-110.1
conda_bcftools: bcftools
conda_bedtools: bedtools-2.31.1
conda_r: RTools
vep_caches_path: /data/dat/vep
vep_data_path: /data/dat/annotationData

