__use_yte__: true
# this config needs to be parsed with YTE
# input configuration
#
samples: config/NSC0000_example_config.tsv
targetfile: config/targets.txt
project: NSC0000_example
#
## status notification email address. Comma separated is OK
#
email: mgaley@uw.edu
#
## output naming customization
prefix_regex: "{SAMPLEID}-NP-{STRATEGY}_{PORE}-{PROJECT_ID}-{OUTSIDE_ID}_{GENE}-{METH}-{MB}"
prefix_lookup: "{sid}-NP-{strat}_{pore}-{project}-{oid}_{gene}-{meth}-{member}"
### the first value of sampleDB_prefix_column_names is processed as the index column.
sampleDB_prefix_format_columns: "sid,strat,pore,project,oid,gene,meth,member"
sampleDB_prefix_column_names: "SampleID,Strategy,Flowcell,Project,ExternalID,TargetGene,Methylation,Member"
#
## input bam file naming string
basecalled_bam_string: "{wildcards.SAMPLEID}*{wildcards.STRATEGY}*"
#
# change explicitLibraries to true to specify library paths in target file rather than sample identifiers
explicitLibraries: true
#
input_dir: /waldo/bam_files_unaligned
final_dir: ?"/n/alignments/" + this["project"]
working_dir: ?"/n/alignments_inprogress/" + this["project"]
#
# resources
threads: 50
#
# target specification
# set allTargets to true to generate all possible files
allTargets: false
allTranscriptomeTargets: false
#optionally change qcCaller to samtools
qcCaller: cramino
# to generate only some files, comment out unwanted analysis steps
# adaptive sampling runs will use the same outputs
outputs: 
  alignBam: true
  clair3: true
  sniffles: true
  svim: true
  cuteSV: true
  CNVcalls: true
  VEP: true
  phaseQC: true
  basicQC: true
#
transcriptomeOutputs:
  alignment: true
  annotation: true
  transcriptome: false
#
# reference data paths
refgenome: /n/dat/hg38/hg38.no_alt.fa
ontmmifile: /n/dat/hg38/hg38.no_alt.mmi
geneAnnotationBed: /n/dat/hg38/resorted.hg38.genes.mergedintervals.bed
transcript_reference: /n/dat/hg38/hg38.ncbiRefSeq.gtf
#
# tool paths
bedfiledir: /n/alignments/bed_targets
clairmodelpath: /n/dat/clair3
vep_caches_path: /n/dat/vep
vep_data_path: /n/dat/annotationData
#
# conda environment names
conda_alignment: alignmentCalling
conda_rust: rust_plus
conda_vep: vep-111.0
conda_bcftools: bcftools-1.19
conda_bedtools: bedtools-2.31.1
conda_r: qdnaseq-1.34.0
conda_gffread: gffread-0.12.7
conda_gffcompare: gffcompare-0.12.6
conda_pychopper: pychopper-2.7.9
conda_stringtie: stringtie-2.2.1