__use_yte__: true
# this config needs to be parsed with YTE
# input configuration
__variables__:
  projectName: NSC0000_example
#
samples: config/NSC0000_example_config.tsv
targetfile: config/targets.txt
project: ?projectName
#
## naming customization
prefix_regex: "{SAMPLEID}-NP-{STRATEGY}-{PROJECT_ID}-{OUTSIDE_ID}_{GENE}-{METH}-{MB}"
prefix_lookup: "{sid}-NP-{strat}-{project}-{oid}_{gene}-{meth}-{member}"
### the first value will not be processed and is assumed to be an index.
sampleDB_prefix_format_columns: "sid,strat,project,oid,gene,meth,member"
sampleDB_prefix_column_names: "SampleID,Strategy,Project,ExternalID,TargetGene,Methylation,Member"
#
# change explicitLibraries to true to specify library paths in target file rather than sample identifiers
explicitLibraries: true
#
input_dir: /waldo/bam_files_unaligned
working_dir: /data/alignments/?projectName
final_dir: /n/alignments/?projectName
#
# resources
threads: 50
#
# target specification
# set allTargets to true to generate all possible files
allTargets: false
#optionally change qcCaller to samtools
qcCaller: cramino
# to generate only some files, comment out unwanted analysis steps
# adaptive sampling runs will use the same outputs
outputs: 
  alignBam: true
  clair3: true
  sniffles: true
  svim: true
  cuteSV: true
  CNVcalls: true
  VEP: true
  phaseQC: true
  basicQC: true
#
# reference data paths
refgenome: /data/dat/hg38/hg38.no_alt.fa
ontmmifile: /data/dat/hg38/hg38.no_alt.mmi
geneAnnotationBed: /data/dat/hg38/resorted.hg38.genes.mergedintervals.bed
#
# tool paths
bedfiledir: /n/alignments/bed_targets
clairmodelpath: /home/shared/resources
vep_caches_path: /data/dat/vep
vep_data_path: /data/dat/annotationData
#
# conda environment names
conda_alignment: alignment_snake
conda_rust: rust_plus
conda_vep: vep-111.0
conda_bcftools: bcftools
conda_bedtools: bedtools-2.31.1
conda_r: RTools